version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "rm -f /rails/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    container_name: rails_container
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle
    environment:
      DATABASE_HOST: db
    env_file: env.development
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: rails_mysql_container
    ports:
      - "3306:3306"
    env_file: env.development
    volumes:
      - mysql_data:/var/lib/mysql
  
  web-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db-test
    env_file: env.test
    depends_on:
      - db-test
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle
  
  db-test:
    image: mysql:8.0
    env_file: env.test

volumes:
  gem_cache:
  mysql_data:
