version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "rm -f /rails/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    image: rails-app
    container_name: rails_container
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle
    env_file: development.env
    depends_on:
      - mysql
      - mysql-test

  mysql:
    image: mysql:8.0
    container_name: rails_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: template_rails_development
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
  
  mysql-test:
    image: mysql:8.0
    container_name: rails_mysql_container_test
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: template_rails_test
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - '3307:3306'

volumes:
  gem_cache:
  mysql_data:
