services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - node_modules_cache:/workspace/node_modules
      - gem_cache:/workspace/vendor/bundle
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      BUNDLE_PATH: /vendor/bundle
      BUNDLER_VERSION: 2.3.7
    tty: true
    stdin_open: true
    command: /bin/sh -c "yarn install && bundle install && sleep infinity"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  node_modules_cache:
  gem_cache:
  db_data:
